version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=klevisson
      - POSTGRESQL_PASSWORD=klevisson
      - POSTGRESQL_DATABASE=apisolid